<?php


/**
 * This class adds structure of 'employer' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Aug 12 17:56:38 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EmployerMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EmployerMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EmployerPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EmployerPeer::TABLE_NAME);
		$tMap->setPhpName('Employer');
		$tMap->setClassname('Employer');

		$tMap->setUseIdGenerator(true);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, 64);

		$tMap->addColumn('CONTACT_PERSON', 'ContactPerson', 'VARCHAR', false, 128);

		$tMap->addColumn('ADDRESS', 'Address', 'VARCHAR', false, 255);

		$tMap->addColumn('PHONE', 'Phone', 'VARCHAR', false, 30);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 64);

		$tMap->addColumn('WEB', 'Web', 'VARCHAR', false, 128);

		$tMap->addForeignKey('REGION_ID', 'RegionId', 'INTEGER', 'region', 'ID', false, null);

		$tMap->addForeignKey('SPECIALITY_ID', 'SpecialityId', 'INTEGER', 'speciality', 'ID', false, null);

		$tMap->addColumn('TARGET_REGIONS', 'TargetRegions', 'VARCHAR', false, 255);

		$tMap->addColumn('SALARY', 'Salary', 'INTEGER', false, null);

		$tMap->addColumn('HOW_MANY_NEEDED', 'HowManyNeeded', 'INTEGER', false, null);

		$tMap->addColumn('SCHEDULE', 'Schedule', 'VARCHAR', false, 64);

		$tMap->addColumn('START_DATE', 'StartDate', 'DATE', false, null);

		$tMap->addColumn('PROVIDE_PLACE', 'ProvidePlace', 'INTEGER', false, null);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null);

		$tMap->addColumn('MAKE_PERMISSION', 'MakePermission', 'INTEGER', false, null);

		$tMap->addColumn('MAKE_REGISTRATION', 'MakeRegistration', 'INTEGER', false, null);

		$tMap->addColumn('EDUCATION', 'Education', 'VARCHAR', false, 64);

		$tMap->addColumn('EXPERIENCE', 'Experience', 'VARCHAR', false, 255);

		$tMap->addColumn('COMPUTER', 'Computer', 'VARCHAR', false, 255);

		$tMap->addColumn('AGE_START', 'AgeStart', 'INTEGER', false, null);

		$tMap->addColumn('AGE_END', 'AgeEnd', 'INTEGER', false, null);

		$tMap->addColumn('GENDER', 'Gender', 'INTEGER', false, null);

		$tMap->addColumn('ADDITIONAL_INFO', 'AdditionalInfo', 'LONGVARCHAR', false, null);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 32);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // EmployerMapBuilder
