<?php

/**
 * Base class that represents a row from the 'worker' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Aug 12 17:56:38 2009
 *
 * @package    lib.model.om
 */
abstract class BaseWorker extends BaseObject  implements Persistent {


  const PEER = 'WorkerPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        WorkerPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the surname field.
	 * @var        string
	 */
	protected $surname;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the father field.
	 * @var        string
	 */
	protected $father;

	/**
	 * The value for the age field.
	 * @var        int
	 */
	protected $age;

	/**
	 * The value for the gender field.
	 * @var        int
	 */
	protected $gender;

	/**
	 * The value for the citizenship_id field.
	 * @var        int
	 */
	protected $citizenship_id;

	/**
	 * The value for the region_id field.
	 * @var        int
	 */
	protected $region_id;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the phone field.
	 * @var        string
	 */
	protected $phone;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the target_regions field.
	 * @var        string
	 */
	protected $target_regions;

	/**
	 * The value for the branch_id field.
	 * @var        int
	 */
	protected $branch_id;

	/**
	 * The value for the speciality_id field.
	 * @var        int
	 */
	protected $speciality_id;

	/**
	 * The value for the salary field.
	 * @var        int
	 */
	protected $salary;

	/**
	 * The value for the schedule field.
	 * @var        string
	 */
	protected $schedule;

	/**
	 * The value for the job_type_id field.
	 * @var        int
	 */
	protected $job_type_id;

	/**
	 * The value for the start_date field.
	 * @var        string
	 */
	protected $start_date;

	/**
	 * The value for the need_place field.
	 * @var        int
	 */
	protected $need_place;

	/**
	 * The value for the has_permission field.
	 * @var        int
	 */
	protected $has_permission;

	/**
	 * The value for the need_registration field.
	 * @var        int
	 */
	protected $need_registration;

	/**
	 * The value for the languages field.
	 * @var        string
	 */
	protected $languages;

	/**
	 * The value for the computer field.
	 * @var        string
	 */
	protected $computer;

	/**
	 * The value for the additional_info field.
	 * @var        string
	 */
	protected $additional_info;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * @var        Citizenship
	 */
	protected $aCitizenship;

	/**
	 * @var        Region
	 */
	protected $aRegion;

	/**
	 * @var        Branch
	 */
	protected $aBranch;

	/**
	 * @var        Speciality
	 */
	protected $aSpeciality;

	/**
	 * @var        JobType
	 */
	protected $aJobType;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseWorker object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [surname] column value.
	 * 
	 * @return     string
	 */
	public function getSurname()
	{
		return $this->surname;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [father] column value.
	 * 
	 * @return     string
	 */
	public function getFather()
	{
		return $this->father;
	}

	/**
	 * Get the [age] column value.
	 * 
	 * @return     int
	 */
	public function getAge()
	{
		return $this->age;
	}

	/**
	 * Get the [gender] column value.
	 * 
	 * @return     int
	 */
	public function getGender()
	{
		return $this->gender;
	}

	/**
	 * Get the [citizenship_id] column value.
	 * 
	 * @return     int
	 */
	public function getCitizenshipId()
	{
		return $this->citizenship_id;
	}

	/**
	 * Get the [region_id] column value.
	 * 
	 * @return     int
	 */
	public function getRegionId()
	{
		return $this->region_id;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [phone] column value.
	 * 
	 * @return     string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [target_regions] column value.
	 * 
	 * @return     string
	 */
	public function getTargetRegions()
	{
		return $this->target_regions;
	}

	/**
	 * Get the [branch_id] column value.
	 * 
	 * @return     int
	 */
	public function getBranchId()
	{
		return $this->branch_id;
	}

	/**
	 * Get the [speciality_id] column value.
	 * 
	 * @return     int
	 */
	public function getSpecialityId()
	{
		return $this->speciality_id;
	}

	/**
	 * Get the [salary] column value.
	 * 
	 * @return     int
	 */
	public function getSalary()
	{
		return $this->salary;
	}

	/**
	 * Get the [schedule] column value.
	 * 
	 * @return     string
	 */
	public function getSchedule()
	{
		return $this->schedule;
	}

	/**
	 * Get the [job_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getJobTypeId()
	{
		return $this->job_type_id;
	}

	/**
	 * Get the [optionally formatted] temporal [start_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStartDate($format = 'Y-m-d')
	{
		if ($this->start_date === null) {
			return null;
		}


		if ($this->start_date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->start_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->start_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [need_place] column value.
	 * 
	 * @return     int
	 */
	public function getNeedPlace()
	{
		return $this->need_place;
	}

	/**
	 * Get the [has_permission] column value.
	 * 
	 * @return     int
	 */
	public function getHasPermission()
	{
		return $this->has_permission;
	}

	/**
	 * Get the [need_registration] column value.
	 * 
	 * @return     int
	 */
	public function getNeedRegistration()
	{
		return $this->need_registration;
	}

	/**
	 * Get the [languages] column value.
	 * 
	 * @return     string
	 */
	public function getLanguages()
	{
		return $this->languages;
	}

	/**
	 * Get the [computer] column value.
	 * 
	 * @return     string
	 */
	public function getComputer()
	{
		return $this->computer;
	}

	/**
	 * Get the [additional_info] column value.
	 * 
	 * @return     string
	 */
	public function getAdditionalInfo()
	{
		return $this->additional_info;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = WorkerPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [surname] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setSurname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->surname !== $v) {
			$this->surname = $v;
			$this->modifiedColumns[] = WorkerPeer::SURNAME;
		}

		return $this;
	} // setSurname()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = WorkerPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [father] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setFather($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->father !== $v) {
			$this->father = $v;
			$this->modifiedColumns[] = WorkerPeer::FATHER;
		}

		return $this;
	} // setFather()

	/**
	 * Set the value of [age] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setAge($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->age !== $v) {
			$this->age = $v;
			$this->modifiedColumns[] = WorkerPeer::AGE;
		}

		return $this;
	} // setAge()

	/**
	 * Set the value of [gender] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setGender($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->gender !== $v) {
			$this->gender = $v;
			$this->modifiedColumns[] = WorkerPeer::GENDER;
		}

		return $this;
	} // setGender()

	/**
	 * Set the value of [citizenship_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setCitizenshipId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->citizenship_id !== $v) {
			$this->citizenship_id = $v;
			$this->modifiedColumns[] = WorkerPeer::CITIZENSHIP_ID;
		}

		if ($this->aCitizenship !== null && $this->aCitizenship->getId() !== $v) {
			$this->aCitizenship = null;
		}

		return $this;
	} // setCitizenshipId()

	/**
	 * Set the value of [region_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setRegionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->region_id !== $v) {
			$this->region_id = $v;
			$this->modifiedColumns[] = WorkerPeer::REGION_ID;
		}

		if ($this->aRegion !== null && $this->aRegion->getId() !== $v) {
			$this->aRegion = null;
		}

		return $this;
	} // setRegionId()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = WorkerPeer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->phone !== $v) {
			$this->phone = $v;
			$this->modifiedColumns[] = WorkerPeer::PHONE;
		}

		return $this;
	} // setPhone()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = WorkerPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [target_regions] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setTargetRegions($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->target_regions !== $v) {
			$this->target_regions = $v;
			$this->modifiedColumns[] = WorkerPeer::TARGET_REGIONS;
		}

		return $this;
	} // setTargetRegions()

	/**
	 * Set the value of [branch_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setBranchId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->branch_id !== $v) {
			$this->branch_id = $v;
			$this->modifiedColumns[] = WorkerPeer::BRANCH_ID;
		}

		if ($this->aBranch !== null && $this->aBranch->getId() !== $v) {
			$this->aBranch = null;
		}

		return $this;
	} // setBranchId()

	/**
	 * Set the value of [speciality_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setSpecialityId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->speciality_id !== $v) {
			$this->speciality_id = $v;
			$this->modifiedColumns[] = WorkerPeer::SPECIALITY_ID;
		}

		if ($this->aSpeciality !== null && $this->aSpeciality->getId() !== $v) {
			$this->aSpeciality = null;
		}

		return $this;
	} // setSpecialityId()

	/**
	 * Set the value of [salary] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setSalary($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->salary !== $v) {
			$this->salary = $v;
			$this->modifiedColumns[] = WorkerPeer::SALARY;
		}

		return $this;
	} // setSalary()

	/**
	 * Set the value of [schedule] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setSchedule($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->schedule !== $v) {
			$this->schedule = $v;
			$this->modifiedColumns[] = WorkerPeer::SCHEDULE;
		}

		return $this;
	} // setSchedule()

	/**
	 * Set the value of [job_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setJobTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->job_type_id !== $v) {
			$this->job_type_id = $v;
			$this->modifiedColumns[] = WorkerPeer::JOB_TYPE_ID;
		}

		if ($this->aJobType !== null && $this->aJobType->getId() !== $v) {
			$this->aJobType = null;
		}

		return $this;
	} // setJobTypeId()

	/**
	 * Sets the value of [start_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setStartDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->start_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->start_date !== null && $tmpDt = new DateTime($this->start_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->start_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = WorkerPeer::START_DATE;
			}
		} // if either are not null

		return $this;
	} // setStartDate()

	/**
	 * Set the value of [need_place] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setNeedPlace($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->need_place !== $v) {
			$this->need_place = $v;
			$this->modifiedColumns[] = WorkerPeer::NEED_PLACE;
		}

		return $this;
	} // setNeedPlace()

	/**
	 * Set the value of [has_permission] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setHasPermission($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->has_permission !== $v) {
			$this->has_permission = $v;
			$this->modifiedColumns[] = WorkerPeer::HAS_PERMISSION;
		}

		return $this;
	} // setHasPermission()

	/**
	 * Set the value of [need_registration] column.
	 * 
	 * @param      int $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setNeedRegistration($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->need_registration !== $v) {
			$this->need_registration = $v;
			$this->modifiedColumns[] = WorkerPeer::NEED_REGISTRATION;
		}

		return $this;
	} // setNeedRegistration()

	/**
	 * Set the value of [languages] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setLanguages($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->languages !== $v) {
			$this->languages = $v;
			$this->modifiedColumns[] = WorkerPeer::LANGUAGES;
		}

		return $this;
	} // setLanguages()

	/**
	 * Set the value of [computer] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setComputer($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->computer !== $v) {
			$this->computer = $v;
			$this->modifiedColumns[] = WorkerPeer::COMPUTER;
		}

		return $this;
	} // setComputer()

	/**
	 * Set the value of [additional_info] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setAdditionalInfo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->additional_info !== $v) {
			$this->additional_info = $v;
			$this->modifiedColumns[] = WorkerPeer::ADDITIONAL_INFO;
		}

		return $this;
	} // setAdditionalInfo()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Worker The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = WorkerPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->surname = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->father = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->age = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->gender = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->citizenship_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->region_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->address = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->phone = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->email = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->target_regions = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->branch_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->speciality_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->salary = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->schedule = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->job_type_id = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->start_date = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->need_place = ($row[$startcol + 18] !== null) ? (int) $row[$startcol + 18] : null;
			$this->has_permission = ($row[$startcol + 19] !== null) ? (int) $row[$startcol + 19] : null;
			$this->need_registration = ($row[$startcol + 20] !== null) ? (int) $row[$startcol + 20] : null;
			$this->languages = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->computer = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->additional_info = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->password = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 25; // 25 = WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Worker object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCitizenship !== null && $this->citizenship_id !== $this->aCitizenship->getId()) {
			$this->aCitizenship = null;
		}
		if ($this->aRegion !== null && $this->region_id !== $this->aRegion->getId()) {
			$this->aRegion = null;
		}
		if ($this->aBranch !== null && $this->branch_id !== $this->aBranch->getId()) {
			$this->aBranch = null;
		}
		if ($this->aSpeciality !== null && $this->speciality_id !== $this->aSpeciality->getId()) {
			$this->aSpeciality = null;
		}
		if ($this->aJobType !== null && $this->job_type_id !== $this->aJobType->getId()) {
			$this->aJobType = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = WorkerPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCitizenship = null;
			$this->aRegion = null;
			$this->aBranch = null;
			$this->aSpeciality = null;
			$this->aJobType = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseWorker:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			WorkerPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseWorker:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseWorker:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseWorker:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			WorkerPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCitizenship !== null) {
				if ($this->aCitizenship->isModified() || $this->aCitizenship->isNew()) {
					$affectedRows += $this->aCitizenship->save($con);
				}
				$this->setCitizenship($this->aCitizenship);
			}

			if ($this->aRegion !== null) {
				if ($this->aRegion->isModified() || $this->aRegion->isNew()) {
					$affectedRows += $this->aRegion->save($con);
				}
				$this->setRegion($this->aRegion);
			}

			if ($this->aBranch !== null) {
				if ($this->aBranch->isModified() || $this->aBranch->isNew()) {
					$affectedRows += $this->aBranch->save($con);
				}
				$this->setBranch($this->aBranch);
			}

			if ($this->aSpeciality !== null) {
				if ($this->aSpeciality->isModified() || $this->aSpeciality->isNew()) {
					$affectedRows += $this->aSpeciality->save($con);
				}
				$this->setSpeciality($this->aSpeciality);
			}

			if ($this->aJobType !== null) {
				if ($this->aJobType->isModified() || $this->aJobType->isNew()) {
					$affectedRows += $this->aJobType->save($con);
				}
				$this->setJobType($this->aJobType);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = WorkerPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = WorkerPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += WorkerPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCitizenship !== null) {
				if (!$this->aCitizenship->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCitizenship->getValidationFailures());
				}
			}

			if ($this->aRegion !== null) {
				if (!$this->aRegion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRegion->getValidationFailures());
				}
			}

			if ($this->aBranch !== null) {
				if (!$this->aBranch->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aBranch->getValidationFailures());
				}
			}

			if ($this->aSpeciality !== null) {
				if (!$this->aSpeciality->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSpeciality->getValidationFailures());
				}
			}

			if ($this->aJobType !== null) {
				if (!$this->aJobType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJobType->getValidationFailures());
				}
			}


			if (($retval = WorkerPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = WorkerPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getSurname();
				break;
			case 2:
				return $this->getName();
				break;
			case 3:
				return $this->getFather();
				break;
			case 4:
				return $this->getAge();
				break;
			case 5:
				return $this->getGender();
				break;
			case 6:
				return $this->getCitizenshipId();
				break;
			case 7:
				return $this->getRegionId();
				break;
			case 8:
				return $this->getAddress();
				break;
			case 9:
				return $this->getPhone();
				break;
			case 10:
				return $this->getEmail();
				break;
			case 11:
				return $this->getTargetRegions();
				break;
			case 12:
				return $this->getBranchId();
				break;
			case 13:
				return $this->getSpecialityId();
				break;
			case 14:
				return $this->getSalary();
				break;
			case 15:
				return $this->getSchedule();
				break;
			case 16:
				return $this->getJobTypeId();
				break;
			case 17:
				return $this->getStartDate();
				break;
			case 18:
				return $this->getNeedPlace();
				break;
			case 19:
				return $this->getHasPermission();
				break;
			case 20:
				return $this->getNeedRegistration();
				break;
			case 21:
				return $this->getLanguages();
				break;
			case 22:
				return $this->getComputer();
				break;
			case 23:
				return $this->getAdditionalInfo();
				break;
			case 24:
				return $this->getPassword();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = WorkerPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getSurname(),
			$keys[2] => $this->getName(),
			$keys[3] => $this->getFather(),
			$keys[4] => $this->getAge(),
			$keys[5] => $this->getGender(),
			$keys[6] => $this->getCitizenshipId(),
			$keys[7] => $this->getRegionId(),
			$keys[8] => $this->getAddress(),
			$keys[9] => $this->getPhone(),
			$keys[10] => $this->getEmail(),
			$keys[11] => $this->getTargetRegions(),
			$keys[12] => $this->getBranchId(),
			$keys[13] => $this->getSpecialityId(),
			$keys[14] => $this->getSalary(),
			$keys[15] => $this->getSchedule(),
			$keys[16] => $this->getJobTypeId(),
			$keys[17] => $this->getStartDate(),
			$keys[18] => $this->getNeedPlace(),
			$keys[19] => $this->getHasPermission(),
			$keys[20] => $this->getNeedRegistration(),
			$keys[21] => $this->getLanguages(),
			$keys[22] => $this->getComputer(),
			$keys[23] => $this->getAdditionalInfo(),
			$keys[24] => $this->getPassword(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = WorkerPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setSurname($value);
				break;
			case 2:
				$this->setName($value);
				break;
			case 3:
				$this->setFather($value);
				break;
			case 4:
				$this->setAge($value);
				break;
			case 5:
				$this->setGender($value);
				break;
			case 6:
				$this->setCitizenshipId($value);
				break;
			case 7:
				$this->setRegionId($value);
				break;
			case 8:
				$this->setAddress($value);
				break;
			case 9:
				$this->setPhone($value);
				break;
			case 10:
				$this->setEmail($value);
				break;
			case 11:
				$this->setTargetRegions($value);
				break;
			case 12:
				$this->setBranchId($value);
				break;
			case 13:
				$this->setSpecialityId($value);
				break;
			case 14:
				$this->setSalary($value);
				break;
			case 15:
				$this->setSchedule($value);
				break;
			case 16:
				$this->setJobTypeId($value);
				break;
			case 17:
				$this->setStartDate($value);
				break;
			case 18:
				$this->setNeedPlace($value);
				break;
			case 19:
				$this->setHasPermission($value);
				break;
			case 20:
				$this->setNeedRegistration($value);
				break;
			case 21:
				$this->setLanguages($value);
				break;
			case 22:
				$this->setComputer($value);
				break;
			case 23:
				$this->setAdditionalInfo($value);
				break;
			case 24:
				$this->setPassword($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = WorkerPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSurname($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFather($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAge($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setGender($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCitizenshipId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setRegionId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setAddress($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPhone($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setEmail($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTargetRegions($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setBranchId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setSpecialityId($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setSalary($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setSchedule($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setJobTypeId($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setStartDate($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setNeedPlace($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setHasPermission($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setNeedRegistration($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setLanguages($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setComputer($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setAdditionalInfo($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setPassword($arr[$keys[24]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(WorkerPeer::DATABASE_NAME);

		if ($this->isColumnModified(WorkerPeer::ID)) $criteria->add(WorkerPeer::ID, $this->id);
		if ($this->isColumnModified(WorkerPeer::SURNAME)) $criteria->add(WorkerPeer::SURNAME, $this->surname);
		if ($this->isColumnModified(WorkerPeer::NAME)) $criteria->add(WorkerPeer::NAME, $this->name);
		if ($this->isColumnModified(WorkerPeer::FATHER)) $criteria->add(WorkerPeer::FATHER, $this->father);
		if ($this->isColumnModified(WorkerPeer::AGE)) $criteria->add(WorkerPeer::AGE, $this->age);
		if ($this->isColumnModified(WorkerPeer::GENDER)) $criteria->add(WorkerPeer::GENDER, $this->gender);
		if ($this->isColumnModified(WorkerPeer::CITIZENSHIP_ID)) $criteria->add(WorkerPeer::CITIZENSHIP_ID, $this->citizenship_id);
		if ($this->isColumnModified(WorkerPeer::REGION_ID)) $criteria->add(WorkerPeer::REGION_ID, $this->region_id);
		if ($this->isColumnModified(WorkerPeer::ADDRESS)) $criteria->add(WorkerPeer::ADDRESS, $this->address);
		if ($this->isColumnModified(WorkerPeer::PHONE)) $criteria->add(WorkerPeer::PHONE, $this->phone);
		if ($this->isColumnModified(WorkerPeer::EMAIL)) $criteria->add(WorkerPeer::EMAIL, $this->email);
		if ($this->isColumnModified(WorkerPeer::TARGET_REGIONS)) $criteria->add(WorkerPeer::TARGET_REGIONS, $this->target_regions);
		if ($this->isColumnModified(WorkerPeer::BRANCH_ID)) $criteria->add(WorkerPeer::BRANCH_ID, $this->branch_id);
		if ($this->isColumnModified(WorkerPeer::SPECIALITY_ID)) $criteria->add(WorkerPeer::SPECIALITY_ID, $this->speciality_id);
		if ($this->isColumnModified(WorkerPeer::SALARY)) $criteria->add(WorkerPeer::SALARY, $this->salary);
		if ($this->isColumnModified(WorkerPeer::SCHEDULE)) $criteria->add(WorkerPeer::SCHEDULE, $this->schedule);
		if ($this->isColumnModified(WorkerPeer::JOB_TYPE_ID)) $criteria->add(WorkerPeer::JOB_TYPE_ID, $this->job_type_id);
		if ($this->isColumnModified(WorkerPeer::START_DATE)) $criteria->add(WorkerPeer::START_DATE, $this->start_date);
		if ($this->isColumnModified(WorkerPeer::NEED_PLACE)) $criteria->add(WorkerPeer::NEED_PLACE, $this->need_place);
		if ($this->isColumnModified(WorkerPeer::HAS_PERMISSION)) $criteria->add(WorkerPeer::HAS_PERMISSION, $this->has_permission);
		if ($this->isColumnModified(WorkerPeer::NEED_REGISTRATION)) $criteria->add(WorkerPeer::NEED_REGISTRATION, $this->need_registration);
		if ($this->isColumnModified(WorkerPeer::LANGUAGES)) $criteria->add(WorkerPeer::LANGUAGES, $this->languages);
		if ($this->isColumnModified(WorkerPeer::COMPUTER)) $criteria->add(WorkerPeer::COMPUTER, $this->computer);
		if ($this->isColumnModified(WorkerPeer::ADDITIONAL_INFO)) $criteria->add(WorkerPeer::ADDITIONAL_INFO, $this->additional_info);
		if ($this->isColumnModified(WorkerPeer::PASSWORD)) $criteria->add(WorkerPeer::PASSWORD, $this->password);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(WorkerPeer::DATABASE_NAME);

		$criteria->add(WorkerPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Worker (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSurname($this->surname);

		$copyObj->setName($this->name);

		$copyObj->setFather($this->father);

		$copyObj->setAge($this->age);

		$copyObj->setGender($this->gender);

		$copyObj->setCitizenshipId($this->citizenship_id);

		$copyObj->setRegionId($this->region_id);

		$copyObj->setAddress($this->address);

		$copyObj->setPhone($this->phone);

		$copyObj->setEmail($this->email);

		$copyObj->setTargetRegions($this->target_regions);

		$copyObj->setBranchId($this->branch_id);

		$copyObj->setSpecialityId($this->speciality_id);

		$copyObj->setSalary($this->salary);

		$copyObj->setSchedule($this->schedule);

		$copyObj->setJobTypeId($this->job_type_id);

		$copyObj->setStartDate($this->start_date);

		$copyObj->setNeedPlace($this->need_place);

		$copyObj->setHasPermission($this->has_permission);

		$copyObj->setNeedRegistration($this->need_registration);

		$copyObj->setLanguages($this->languages);

		$copyObj->setComputer($this->computer);

		$copyObj->setAdditionalInfo($this->additional_info);

		$copyObj->setPassword($this->password);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Worker Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     WorkerPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new WorkerPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Citizenship object.
	 *
	 * @param      Citizenship $v
	 * @return     Worker The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCitizenship(Citizenship $v = null)
	{
		if ($v === null) {
			$this->setCitizenshipId(NULL);
		} else {
			$this->setCitizenshipId($v->getId());
		}

		$this->aCitizenship = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Citizenship object, it will not be re-added.
		if ($v !== null) {
			$v->addWorker($this);
		}

		return $this;
	}


	/**
	 * Get the associated Citizenship object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Citizenship The associated Citizenship object.
	 * @throws     PropelException
	 */
	public function getCitizenship(PropelPDO $con = null)
	{
		if ($this->aCitizenship === null && ($this->citizenship_id !== null)) {
			$c = new Criteria(CitizenshipPeer::DATABASE_NAME);
			$c->add(CitizenshipPeer::ID, $this->citizenship_id);
			$this->aCitizenship = CitizenshipPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCitizenship->addWorkers($this);
			 */
		}
		return $this->aCitizenship;
	}

	/**
	 * Declares an association between this object and a Region object.
	 *
	 * @param      Region $v
	 * @return     Worker The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRegion(Region $v = null)
	{
		if ($v === null) {
			$this->setRegionId(NULL);
		} else {
			$this->setRegionId($v->getId());
		}

		$this->aRegion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Region object, it will not be re-added.
		if ($v !== null) {
			$v->addWorker($this);
		}

		return $this;
	}


	/**
	 * Get the associated Region object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Region The associated Region object.
	 * @throws     PropelException
	 */
	public function getRegion(PropelPDO $con = null)
	{
		if ($this->aRegion === null && ($this->region_id !== null)) {
			$c = new Criteria(RegionPeer::DATABASE_NAME);
			$c->add(RegionPeer::ID, $this->region_id);
			$this->aRegion = RegionPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRegion->addWorkers($this);
			 */
		}
		return $this->aRegion;
	}

	/**
	 * Declares an association between this object and a Branch object.
	 *
	 * @param      Branch $v
	 * @return     Worker The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setBranch(Branch $v = null)
	{
		if ($v === null) {
			$this->setBranchId(NULL);
		} else {
			$this->setBranchId($v->getId());
		}

		$this->aBranch = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Branch object, it will not be re-added.
		if ($v !== null) {
			$v->addWorker($this);
		}

		return $this;
	}


	/**
	 * Get the associated Branch object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Branch The associated Branch object.
	 * @throws     PropelException
	 */
	public function getBranch(PropelPDO $con = null)
	{
		if ($this->aBranch === null && ($this->branch_id !== null)) {
			$c = new Criteria(BranchPeer::DATABASE_NAME);
			$c->add(BranchPeer::ID, $this->branch_id);
			$this->aBranch = BranchPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aBranch->addWorkers($this);
			 */
		}
		return $this->aBranch;
	}

	/**
	 * Declares an association between this object and a Speciality object.
	 *
	 * @param      Speciality $v
	 * @return     Worker The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSpeciality(Speciality $v = null)
	{
		if ($v === null) {
			$this->setSpecialityId(NULL);
		} else {
			$this->setSpecialityId($v->getId());
		}

		$this->aSpeciality = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Speciality object, it will not be re-added.
		if ($v !== null) {
			$v->addWorker($this);
		}

		return $this;
	}


	/**
	 * Get the associated Speciality object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Speciality The associated Speciality object.
	 * @throws     PropelException
	 */
	public function getSpeciality(PropelPDO $con = null)
	{
		if ($this->aSpeciality === null && ($this->speciality_id !== null)) {
			$c = new Criteria(SpecialityPeer::DATABASE_NAME);
			$c->add(SpecialityPeer::ID, $this->speciality_id);
			$this->aSpeciality = SpecialityPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSpeciality->addWorkers($this);
			 */
		}
		return $this->aSpeciality;
	}

	/**
	 * Declares an association between this object and a JobType object.
	 *
	 * @param      JobType $v
	 * @return     Worker The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJobType(JobType $v = null)
	{
		if ($v === null) {
			$this->setJobTypeId(NULL);
		} else {
			$this->setJobTypeId($v->getId());
		}

		$this->aJobType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the JobType object, it will not be re-added.
		if ($v !== null) {
			$v->addWorker($this);
		}

		return $this;
	}


	/**
	 * Get the associated JobType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     JobType The associated JobType object.
	 * @throws     PropelException
	 */
	public function getJobType(PropelPDO $con = null)
	{
		if ($this->aJobType === null && ($this->job_type_id !== null)) {
			$c = new Criteria(JobTypePeer::DATABASE_NAME);
			$c->add(JobTypePeer::ID, $this->job_type_id);
			$this->aJobType = JobTypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aJobType->addWorkers($this);
			 */
		}
		return $this->aJobType;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCitizenship = null;
			$this->aRegion = null;
			$this->aBranch = null;
			$this->aSpeciality = null;
			$this->aJobType = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseWorker:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseWorker::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseWorker
