<?php

/**
 * Base static class for performing query and update operations on the 'worker' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Aug 12 17:56:38 2009
 *
 * @package    lib.model.om
 */
abstract class BaseWorkerPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'worker';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Worker';

	/** The total number of columns. */
	const NUM_COLUMNS = 25;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'worker.ID';

	/** the column name for the SURNAME field */
	const SURNAME = 'worker.SURNAME';

	/** the column name for the NAME field */
	const NAME = 'worker.NAME';

	/** the column name for the FATHER field */
	const FATHER = 'worker.FATHER';

	/** the column name for the AGE field */
	const AGE = 'worker.AGE';

	/** the column name for the GENDER field */
	const GENDER = 'worker.GENDER';

	/** the column name for the CITIZENSHIP_ID field */
	const CITIZENSHIP_ID = 'worker.CITIZENSHIP_ID';

	/** the column name for the REGION_ID field */
	const REGION_ID = 'worker.REGION_ID';

	/** the column name for the ADDRESS field */
	const ADDRESS = 'worker.ADDRESS';

	/** the column name for the PHONE field */
	const PHONE = 'worker.PHONE';

	/** the column name for the EMAIL field */
	const EMAIL = 'worker.EMAIL';

	/** the column name for the TARGET_REGIONS field */
	const TARGET_REGIONS = 'worker.TARGET_REGIONS';

	/** the column name for the BRANCH_ID field */
	const BRANCH_ID = 'worker.BRANCH_ID';

	/** the column name for the SPECIALITY_ID field */
	const SPECIALITY_ID = 'worker.SPECIALITY_ID';

	/** the column name for the SALARY field */
	const SALARY = 'worker.SALARY';

	/** the column name for the SCHEDULE field */
	const SCHEDULE = 'worker.SCHEDULE';

	/** the column name for the JOB_TYPE_ID field */
	const JOB_TYPE_ID = 'worker.JOB_TYPE_ID';

	/** the column name for the START_DATE field */
	const START_DATE = 'worker.START_DATE';

	/** the column name for the NEED_PLACE field */
	const NEED_PLACE = 'worker.NEED_PLACE';

	/** the column name for the HAS_PERMISSION field */
	const HAS_PERMISSION = 'worker.HAS_PERMISSION';

	/** the column name for the NEED_REGISTRATION field */
	const NEED_REGISTRATION = 'worker.NEED_REGISTRATION';

	/** the column name for the LANGUAGES field */
	const LANGUAGES = 'worker.LANGUAGES';

	/** the column name for the COMPUTER field */
	const COMPUTER = 'worker.COMPUTER';

	/** the column name for the ADDITIONAL_INFO field */
	const ADDITIONAL_INFO = 'worker.ADDITIONAL_INFO';

	/** the column name for the PASSWORD field */
	const PASSWORD = 'worker.PASSWORD';

	/**
	 * An identiy map to hold any loaded instances of Worker objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Worker[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Surname', 'Name', 'Father', 'Age', 'Gender', 'CitizenshipId', 'RegionId', 'Address', 'Phone', 'Email', 'TargetRegions', 'BranchId', 'SpecialityId', 'Salary', 'Schedule', 'JobTypeId', 'StartDate', 'NeedPlace', 'HasPermission', 'NeedRegistration', 'Languages', 'Computer', 'AdditionalInfo', 'Password', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'surname', 'name', 'father', 'age', 'gender', 'citizenshipId', 'regionId', 'address', 'phone', 'email', 'targetRegions', 'branchId', 'specialityId', 'salary', 'schedule', 'jobTypeId', 'startDate', 'needPlace', 'hasPermission', 'needRegistration', 'languages', 'computer', 'additionalInfo', 'password', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::SURNAME, self::NAME, self::FATHER, self::AGE, self::GENDER, self::CITIZENSHIP_ID, self::REGION_ID, self::ADDRESS, self::PHONE, self::EMAIL, self::TARGET_REGIONS, self::BRANCH_ID, self::SPECIALITY_ID, self::SALARY, self::SCHEDULE, self::JOB_TYPE_ID, self::START_DATE, self::NEED_PLACE, self::HAS_PERMISSION, self::NEED_REGISTRATION, self::LANGUAGES, self::COMPUTER, self::ADDITIONAL_INFO, self::PASSWORD, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'surname', 'name', 'father', 'age', 'gender', 'citizenship_id', 'region_id', 'address', 'phone', 'email', 'target_regions', 'branch_id', 'speciality_id', 'salary', 'schedule', 'job_type_id', 'start_date', 'need_place', 'has_permission', 'need_registration', 'languages', 'computer', 'additional_info', 'password', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Surname' => 1, 'Name' => 2, 'Father' => 3, 'Age' => 4, 'Gender' => 5, 'CitizenshipId' => 6, 'RegionId' => 7, 'Address' => 8, 'Phone' => 9, 'Email' => 10, 'TargetRegions' => 11, 'BranchId' => 12, 'SpecialityId' => 13, 'Salary' => 14, 'Schedule' => 15, 'JobTypeId' => 16, 'StartDate' => 17, 'NeedPlace' => 18, 'HasPermission' => 19, 'NeedRegistration' => 20, 'Languages' => 21, 'Computer' => 22, 'AdditionalInfo' => 23, 'Password' => 24, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'surname' => 1, 'name' => 2, 'father' => 3, 'age' => 4, 'gender' => 5, 'citizenshipId' => 6, 'regionId' => 7, 'address' => 8, 'phone' => 9, 'email' => 10, 'targetRegions' => 11, 'branchId' => 12, 'specialityId' => 13, 'salary' => 14, 'schedule' => 15, 'jobTypeId' => 16, 'startDate' => 17, 'needPlace' => 18, 'hasPermission' => 19, 'needRegistration' => 20, 'languages' => 21, 'computer' => 22, 'additionalInfo' => 23, 'password' => 24, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::SURNAME => 1, self::NAME => 2, self::FATHER => 3, self::AGE => 4, self::GENDER => 5, self::CITIZENSHIP_ID => 6, self::REGION_ID => 7, self::ADDRESS => 8, self::PHONE => 9, self::EMAIL => 10, self::TARGET_REGIONS => 11, self::BRANCH_ID => 12, self::SPECIALITY_ID => 13, self::SALARY => 14, self::SCHEDULE => 15, self::JOB_TYPE_ID => 16, self::START_DATE => 17, self::NEED_PLACE => 18, self::HAS_PERMISSION => 19, self::NEED_REGISTRATION => 20, self::LANGUAGES => 21, self::COMPUTER => 22, self::ADDITIONAL_INFO => 23, self::PASSWORD => 24, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'surname' => 1, 'name' => 2, 'father' => 3, 'age' => 4, 'gender' => 5, 'citizenship_id' => 6, 'region_id' => 7, 'address' => 8, 'phone' => 9, 'email' => 10, 'target_regions' => 11, 'branch_id' => 12, 'speciality_id' => 13, 'salary' => 14, 'schedule' => 15, 'job_type_id' => 16, 'start_date' => 17, 'need_place' => 18, 'has_permission' => 19, 'need_registration' => 20, 'languages' => 21, 'computer' => 22, 'additional_info' => 23, 'password' => 24, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new WorkerMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. WorkerPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(WorkerPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(WorkerPeer::ID);

		$criteria->addSelectColumn(WorkerPeer::SURNAME);

		$criteria->addSelectColumn(WorkerPeer::NAME);

		$criteria->addSelectColumn(WorkerPeer::FATHER);

		$criteria->addSelectColumn(WorkerPeer::AGE);

		$criteria->addSelectColumn(WorkerPeer::GENDER);

		$criteria->addSelectColumn(WorkerPeer::CITIZENSHIP_ID);

		$criteria->addSelectColumn(WorkerPeer::REGION_ID);

		$criteria->addSelectColumn(WorkerPeer::ADDRESS);

		$criteria->addSelectColumn(WorkerPeer::PHONE);

		$criteria->addSelectColumn(WorkerPeer::EMAIL);

		$criteria->addSelectColumn(WorkerPeer::TARGET_REGIONS);

		$criteria->addSelectColumn(WorkerPeer::BRANCH_ID);

		$criteria->addSelectColumn(WorkerPeer::SPECIALITY_ID);

		$criteria->addSelectColumn(WorkerPeer::SALARY);

		$criteria->addSelectColumn(WorkerPeer::SCHEDULE);

		$criteria->addSelectColumn(WorkerPeer::JOB_TYPE_ID);

		$criteria->addSelectColumn(WorkerPeer::START_DATE);

		$criteria->addSelectColumn(WorkerPeer::NEED_PLACE);

		$criteria->addSelectColumn(WorkerPeer::HAS_PERMISSION);

		$criteria->addSelectColumn(WorkerPeer::NEED_REGISTRATION);

		$criteria->addSelectColumn(WorkerPeer::LANGUAGES);

		$criteria->addSelectColumn(WorkerPeer::COMPUTER);

		$criteria->addSelectColumn(WorkerPeer::ADDITIONAL_INFO);

		$criteria->addSelectColumn(WorkerPeer::PASSWORD);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Worker
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = WorkerPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return WorkerPeer::populateObjects(WorkerPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			WorkerPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Worker $value A Worker object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Worker $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Worker object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Worker) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Worker object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Worker Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = WorkerPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = WorkerPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				WorkerPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Citizenship table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCitizenship(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Region table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinRegion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Branch table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinBranch(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Speciality table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinSpeciality(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related JobType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinJobType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with their Citizenship objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCitizenship(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);
		CitizenshipPeer::addSelectColumns($c);

		$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CitizenshipPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Worker) to $obj2 (Citizenship)
				$obj2->addWorker($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with their Region objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinRegion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);
		RegionPeer::addSelectColumns($c);

		$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = RegionPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = RegionPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					RegionPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Worker) to $obj2 (Region)
				$obj2->addWorker($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with their Branch objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinBranch(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);
		BranchPeer::addSelectColumns($c);

		$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = BranchPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = BranchPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					BranchPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Worker) to $obj2 (Branch)
				$obj2->addWorker($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with their Speciality objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinSpeciality(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);
		SpecialityPeer::addSelectColumns($c);

		$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = SpecialityPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = SpecialityPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					SpecialityPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Worker) to $obj2 (Speciality)
				$obj2->addWorker($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with their JobType objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinJobType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);
		JobTypePeer::addSelectColumns($c);

		$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = JobTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = JobTypePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					JobTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Worker) to $obj2 (JobType)
				$obj2->addWorker($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(WorkerPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
		$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
		$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
		$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
		$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Worker objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		CitizenshipPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CitizenshipPeer::NUM_COLUMNS - CitizenshipPeer::NUM_LAZY_LOAD_COLUMNS);

		RegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (RegionPeer::NUM_COLUMNS - RegionPeer::NUM_LAZY_LOAD_COLUMNS);

		BranchPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (BranchPeer::NUM_COLUMNS - BranchPeer::NUM_LAZY_LOAD_COLUMNS);

		SpecialityPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (SpecialityPeer::NUM_COLUMNS - SpecialityPeer::NUM_LAZY_LOAD_COLUMNS);

		JobTypePeer::addSelectColumns($c);
		$startcol7 = $startcol6 + (JobTypePeer::NUM_COLUMNS - JobTypePeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
		$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
		$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
		$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
		$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Citizenship rows

			$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CitizenshipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Citizenship)
				$obj2->addWorker($obj1);
			} // if joined row not null

			// Add objects for joined Region rows

			$key3 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = RegionPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = RegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					RegionPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Region)
				$obj3->addWorker($obj1);
			} // if joined row not null

			// Add objects for joined Branch rows

			$key4 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = BranchPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = BranchPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					BranchPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Branch)
				$obj4->addWorker($obj1);
			} // if joined row not null

			// Add objects for joined Speciality rows

			$key5 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = SpecialityPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = SpecialityPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					SpecialityPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (Speciality)
				$obj5->addWorker($obj1);
			} // if joined row not null

			// Add objects for joined JobType rows

			$key6 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol6);
			if ($key6 !== null) {
				$obj6 = JobTypePeer::getInstanceFromPool($key6);
				if (!$obj6) {

					$omClass = JobTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj6 = new $cls();
					$obj6->hydrate($row, $startcol6);
					JobTypePeer::addInstanceToPool($obj6, $key6);
				} // if obj6 loaded

				// Add the $obj1 (Worker) to the collection in $obj6 (JobType)
				$obj6->addWorker($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Citizenship table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCitizenship(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Region table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptRegion(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Branch table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptBranch(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Speciality table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptSpeciality(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related JobType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptJobType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			WorkerPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$criteria->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseWorkerPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with all related objects except Citizenship.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCitizenship(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		RegionPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (RegionPeer::NUM_COLUMNS - RegionPeer::NUM_LAZY_LOAD_COLUMNS);

		BranchPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (BranchPeer::NUM_COLUMNS - BranchPeer::NUM_LAZY_LOAD_COLUMNS);

		SpecialityPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SpecialityPeer::NUM_COLUMNS - SpecialityPeer::NUM_LAZY_LOAD_COLUMNS);

		JobTypePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (JobTypePeer::NUM_COLUMNS - JobTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Region rows

				$key2 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = RegionPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = RegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					RegionPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Region)
				$obj2->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Branch rows

				$key3 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = BranchPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = BranchPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					BranchPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Branch)
				$obj3->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Speciality rows

				$key4 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SpecialityPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SpecialityPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SpecialityPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Speciality)
				$obj4->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined JobType rows

				$key5 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = JobTypePeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = JobTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					JobTypePeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (JobType)
				$obj5->addWorker($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with all related objects except Region.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptRegion(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		CitizenshipPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CitizenshipPeer::NUM_COLUMNS - CitizenshipPeer::NUM_LAZY_LOAD_COLUMNS);

		BranchPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (BranchPeer::NUM_COLUMNS - BranchPeer::NUM_LAZY_LOAD_COLUMNS);

		SpecialityPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SpecialityPeer::NUM_COLUMNS - SpecialityPeer::NUM_LAZY_LOAD_COLUMNS);

		JobTypePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (JobTypePeer::NUM_COLUMNS - JobTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Citizenship rows

				$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CitizenshipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Citizenship)
				$obj2->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Branch rows

				$key3 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = BranchPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = BranchPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					BranchPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Branch)
				$obj3->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Speciality rows

				$key4 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SpecialityPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SpecialityPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SpecialityPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Speciality)
				$obj4->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined JobType rows

				$key5 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = JobTypePeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = JobTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					JobTypePeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (JobType)
				$obj5->addWorker($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with all related objects except Branch.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptBranch(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		CitizenshipPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CitizenshipPeer::NUM_COLUMNS - CitizenshipPeer::NUM_LAZY_LOAD_COLUMNS);

		RegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (RegionPeer::NUM_COLUMNS - RegionPeer::NUM_LAZY_LOAD_COLUMNS);

		SpecialityPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (SpecialityPeer::NUM_COLUMNS - SpecialityPeer::NUM_LAZY_LOAD_COLUMNS);

		JobTypePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (JobTypePeer::NUM_COLUMNS - JobTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Citizenship rows

				$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CitizenshipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Citizenship)
				$obj2->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Region rows

				$key3 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = RegionPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = RegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					RegionPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Region)
				$obj3->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Speciality rows

				$key4 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = SpecialityPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = SpecialityPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					SpecialityPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Speciality)
				$obj4->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined JobType rows

				$key5 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = JobTypePeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = JobTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					JobTypePeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (JobType)
				$obj5->addWorker($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with all related objects except Speciality.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptSpeciality(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		CitizenshipPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CitizenshipPeer::NUM_COLUMNS - CitizenshipPeer::NUM_LAZY_LOAD_COLUMNS);

		RegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (RegionPeer::NUM_COLUMNS - RegionPeer::NUM_LAZY_LOAD_COLUMNS);

		BranchPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (BranchPeer::NUM_COLUMNS - BranchPeer::NUM_LAZY_LOAD_COLUMNS);

		JobTypePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (JobTypePeer::NUM_COLUMNS - JobTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::JOB_TYPE_ID,), array(JobTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Citizenship rows

				$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CitizenshipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Citizenship)
				$obj2->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Region rows

				$key3 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = RegionPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = RegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					RegionPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Region)
				$obj3->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Branch rows

				$key4 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = BranchPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = BranchPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					BranchPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Branch)
				$obj4->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined JobType rows

				$key5 = JobTypePeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = JobTypePeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = JobTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					JobTypePeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (JobType)
				$obj5->addWorker($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Worker objects pre-filled with all related objects except JobType.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Worker objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptJobType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		WorkerPeer::addSelectColumns($c);
		$startcol2 = (WorkerPeer::NUM_COLUMNS - WorkerPeer::NUM_LAZY_LOAD_COLUMNS);

		CitizenshipPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (CitizenshipPeer::NUM_COLUMNS - CitizenshipPeer::NUM_LAZY_LOAD_COLUMNS);

		RegionPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (RegionPeer::NUM_COLUMNS - RegionPeer::NUM_LAZY_LOAD_COLUMNS);

		BranchPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (BranchPeer::NUM_COLUMNS - BranchPeer::NUM_LAZY_LOAD_COLUMNS);

		SpecialityPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (SpecialityPeer::NUM_COLUMNS - SpecialityPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(WorkerPeer::CITIZENSHIP_ID,), array(CitizenshipPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::REGION_ID,), array(RegionPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::BRANCH_ID,), array(BranchPeer::ID,), $join_behavior);
				$c->addJoin(array(WorkerPeer::SPECIALITY_ID,), array(SpecialityPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = WorkerPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = WorkerPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = WorkerPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				WorkerPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Citizenship rows

				$key2 = CitizenshipPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = CitizenshipPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = CitizenshipPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					CitizenshipPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Worker) to the collection in $obj2 (Citizenship)
				$obj2->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Region rows

				$key3 = RegionPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = RegionPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = RegionPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					RegionPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Worker) to the collection in $obj3 (Region)
				$obj3->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Branch rows

				$key4 = BranchPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = BranchPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = BranchPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					BranchPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Worker) to the collection in $obj4 (Branch)
				$obj4->addWorker($obj1);

			} // if joined row is not null

				// Add objects for joined Speciality rows

				$key5 = SpecialityPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = SpecialityPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$omClass = SpecialityPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					SpecialityPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Worker) to the collection in $obj5 (Speciality)
				$obj5->addWorker($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return WorkerPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Worker or Criteria object.
	 *
	 * @param      mixed $values Criteria or Worker object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseWorkerPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Worker object
		}

		if ($criteria->containsKey(WorkerPeer::ID) && $criteria->keyContainsValue(WorkerPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.WorkerPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseWorkerPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Worker or Criteria object.
	 *
	 * @param      mixed $values Criteria or Worker object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseWorkerPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseWorkerPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(WorkerPeer::ID);
			$selectCriteria->add(WorkerPeer::ID, $criteria->remove(WorkerPeer::ID), $comparison);

		} else { // $values is Worker object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseWorkerPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseWorkerPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the worker table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(WorkerPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Worker or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Worker object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			WorkerPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Worker) {
			// invalidate the cache for this single object
			WorkerPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(WorkerPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				WorkerPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Worker object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Worker $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Worker $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(WorkerPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(WorkerPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(WorkerPeer::DATABASE_NAME, WorkerPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = WorkerPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Worker
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = WorkerPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(WorkerPeer::DATABASE_NAME);
		$criteria->add(WorkerPeer::ID, $pk);

		$v = WorkerPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(WorkerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(WorkerPeer::DATABASE_NAME);
			$criteria->add(WorkerPeer::ID, $pks, Criteria::IN);
			$objs = WorkerPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseWorkerPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the WorkerPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the WorkerPeer class:
//
// Propel::getDatabaseMap(WorkerPeer::DATABASE_NAME)->addTableBuilder(WorkerPeer::TABLE_NAME, WorkerPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseWorkerPeer::DATABASE_NAME)->addTableBuilder(BaseWorkerPeer::TABLE_NAME, BaseWorkerPeer::getMapBuilder());

